name: Test Schedule

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo "Scheduled workflow is working!"
          echo "UTC time: $(date -u)"
